export { default as authRouter } from './authRouter'
export { default as userRouter } from './userRouter'
export { default as premisesRouter } from './premisesRouter'
export { default as zoneRouter } from './zoneRouter'
export { default as boardRouter } from './boardRouter'
export { default as routineRouter } from './routineRouter'
export { default as widgetRouter } from './widgetRouter'
