export { default as authRouter } from './authRouter'
export { default as userRouter } from './userRouter'
export { default as projectRouter } from './projectRouter'
export { default as boardRouter } from './boardRouter'
export { default as routineRouter } from './routineRouter'
export { default as widgetRouter } from './widgetRouter'
